services:
  - type: web
    name: rockpaperscissors
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    envVars:
      - key: GIN_MODE
        value: release
      - key: PORT
        value: 8080 